CREATE TABLE IF NOT EXISTS Content (
  id TEXT PRIMARY KEY,
  data TEXT
);
CREATE TABLE IF NOT EXISTS Settings (
  id TEXT PRIMARY KEY,
  data TEXT
);
CREATE TABLE IF NOT EXISTS AdminUser (
  id TEXT PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  must_change_password BOOLEAN DEFAULT TRUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Sessions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  expires_at DATETIME NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES AdminUser(id)
);
